# Generated by Django 3.0.6 on 2020-06-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
    ]
