# Generated by Django 3.0.6 on 2020-06-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0003_auto_20200614_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_main',
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основная секция')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.Article')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.Section')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='articles',

        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(through='m2m.Relations', to='m2m.Article'),
        ),
    ]
