# Generated by Django 3.0.6 on 2020-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0004_auto_20200614_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={'verbose_name': 'Секция в статье', 'verbose_name_plural': 'Секции в статье'},
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(through='m2m.Relations', to='m2m.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Секция'),
        ),
    ]
