# Generated by Django 3.0.6 on 2020-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0005_auto_20200614_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(related_name='art', through='m2m.Relations', to='m2m.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='sect', through='m2m.Relations', to='m2m.Article'),
        ),
    ]
