# Generated by Django 3.0.6 on 2020-06-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0006_auto_20200615_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={'ordering': ['sections__name'], 'verbose_name': 'Секция в статье', 'verbose_name_plural': 'Секции в статье'},
        ),
    ]
