# Generated by Django 3.0.6 on 2020-06-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0007_auto_20200616_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={'ordering': ['is_main', 'sections__name'], 'verbose_name': 'Секция в статье', 'verbose_name_plural': 'Секции в статье'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='sections',
        ),
    ]
