# Generated by Django 3.0.6 on 2020-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0008_auto_20200617_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(related_name='art', through='m2m.Relations', to='m2m.Section'),
        ),
    ]
