# Generated by Django 3.0.6 on 2020-06-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0009_auto_20200617_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={'ordering': ['-is_main', 'sections__name'], 'verbose_name': 'Секция в статье', 'verbose_name_plural': 'Секции в статье'},
        ),
    ]
